name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: chris-short/github-action-git-submodules@v0.1.0
    - name: Git Submodules Init
      run: git submodule init && git submodule update
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
