name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git submodule
      run: git submodule init && git submodule update
    - name: install dependencies
      run: lein deps
    - name: run tests
      run: lein test
